# Generated by Django 4.0.4 on 2022-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username1',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='username1',
            name='surname',
            field=models.CharField(max_length=20),
        ),
    ]
