# Generated by Django 4.0.4 on 2022-06-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_username1_name_alter_username1_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='username1',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='username1',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
