# Generated by Django 4.0.4 on 2022-06-13 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_username1_bio_username1_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username1',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='username1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='username1',
            name='image',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('skill', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
