# Generated by Django 4.0.4 on 2022-06-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_username1_name_alter_username1_surname'),
        ('qizil', '0002_gold_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gold',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qizil.gold')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.username1')),
            ],
        ),
    ]
